### ISSUE TITLE
Files are uploaded multiple time

### ISSUE THREAD

**Issue by QuLogic** [TobiasTheViking/googledriveannex#8]
Following #7, I restarted the copy. Instead of continuing from where it left off, the _same_ files were uploaded again. If I go look at my Drive, there are several duplicate folders (e.g, `0f`, `0f`, `0F`, `0F`, etc.) all containing the same hashed files.

**Comment by hugoroy** [comment]
:+1:

**Comment by giomasce** [comment]
I have similar problems. Many directories get created more than once. Moreover it often appears that, after I have uploaded a file to the Google Drive remote, I cannot get it from there (the file is marked as being present on Drive, but `git annex get` requests fail and `git annex fsck` says the file is not actually present). I suspect that the Google Drive plugin is confused by multiple subdirectories having the same name (and it ends up checking a wrong one, thus not finding the file).

I am not an expert of Google Drive, but will try to perform more accurate checks.

**Comment by giomasce** [comment]
The two commits here above should fix the problem and also automatically heal a remote that has already been hit. Everything is still highly experimental, even more considering that I just discovered how to use Google Drive API (mostly by reading docs examples and trial and error). However first tests indicate that everything is working as expected.

I will report here when I have more precise results. In the meantime my Google Drive remote is kept in `untrusted` mode.

**Comment by QuLogic** [comment]
Since you mentioned it, I had a look at the fork network here, and it looks like @marek-j has some similar(/redundant?) changes that you two might want to compare/merge.

**Comment by hugoroy** [comment]
For info: https://github.com/TobiasTheViking/googledriveannex/pull/5/files#diff-8b1b12b37e7ca5163ca4a05cfcd8d5cdR209 cc @marek-j

**Comment by giomasce** [comment]
How annoying, I did not notice that @marek-j had already fixed.

However, my fix is different from his/her since:
- the repository layout is not changed (the two levels of folders are kept; this is probably not a good idea, since it makes everything slower due to the latency of the Drive API);
- I included some code that performs some basic self healing of a repository that already has duplicated folders in it (this code is probably not perfect and for sure it risks encountering race conditions if more than one operation is running at the same time).

**Comment by giomasce** [comment]
However, transitioning to a flat directory is probably more clever, provided that this does not bring performance issues. I do not think it should, but [asked on SO](http://stackoverflow.com/q/27410444/807307) to know more (I am not an expert of Google Drive).

I will try to write some code to convert a repository from the three-level style to the flat style, because I would really avoid uploading all my documents again (and it should not be difficult to fix the repository).

**Comment by marek-j** [comment]
Hi, my first experiments showed there are no performance issues using the API with many files in one folder. I do not have numbers though. 
However, once I had two conditions in the query string in the wrong order and the huge performance penalty indicated that the query string is directly converted to a join gone wrong ;-).
In fact I am pretty sure that googledrive is a database and not a filesystem. Folders are just attributes for files. 
However, I stopped development on the googledrive plugin as I encountered this bug https://code.google.com/p/google-api-python-client/issues/detail?id=231
that was present in the googledrive backend and prevented me from uploading large files. This was a dealbreaker for me and thus I switched to hubic. And the hubic plugin is working VERY well. It has been uploading for weeks across re-connections of my DSL connection without a huckup.

**Comment by QuLogic** [comment]
@giomasce BTW, will that healing stuff deal with recovering from 5xx errors like #7?

@marek-j That bug appears fixed now, though I guess you have no need to switch back.

**Comment by giomasce** [comment]
@QuLogic No, it just moves around files and folders in order to have exactly one thing with the same name in each folder. I do not know exactly which kind of error happen in #7, but I do not think my code would handle something like that.

**Comment by QuLogic** [comment]
@giomasce I see you've ported some of your work on top of @marek-j's. Since it's over top of the flattened setup, does the healing procedure unflatten things?

**Comment by QuLogic** [comment]
So I merged in to [my fork](https://github.com/QuLogic/googledriveannex) both of your work, and it's working pretty well for me. Did a couple syncs and things were not uploaded twice. Also, didn't encounter any 500 errors that killed everything.

**Comment by giomasce** [comment]
Not really. At the moment the (expected and so far observed) behavior of my `retry500` branch is:
- Create files directly in the base path (not in the subdirectories);
- Search for files _in the whole Drive_, even out of the base directory (the search is performed just by filename, with no regard of the parent directory); this should not be a problem as long as all files named `GPGHMACSHA1--*` are legitimate git-annex files (with content according to the filename); if instead someone can inject (for example via a shared Drive folder) a similarly named file, but with wrong content, then the remote gets poisoned (although everything is verifiable with `git annex fsck`);
- Files are healed in the sense that if there are more files with the same name, then all but one randomly selected are deleted; this is not deterministic, so if two `googledriveannex` instances are working at the same time on the same Drive account they may delete all the copies of a given file (and location log would be wrong thereafter: both instances would be convinced that the file is still present on the remote). File healing is implemented for folders as well, but at the moment is probably never executed (since there are no subfolder levels).

Of course the current implementation is lacking from many viewpoints. First, there are the problems said above (remote poisoning and race issue). Then, there are some very dirty tricks in `findInFolder()`, whose behavior wrongly depends on whether the requested item is in the root folder or not. Now that I think about it, this could even cause problems if the base folder is not directly in the root folder; this is not my case, so I did not test it.

Anyway, while my code is working for me, please be aware that is very far from being reliable in other situations.

**Comment by giomasce** [comment]
By the way, I am pretty sure that if the remote base folder is not directly in the root folder of the Drive and there are other folders in the Drive with the same name, the healing procedure _will_ mess up things. So please be aware of how things work before using my code if there are important things in your Drive.

**Comment by QuLogic** [comment]
> Search for files in the whole Drive, even out of the base directory

I wasn't sure why you changed that in the `retryon500` branch? It wasn't like that on your `master`, was it? Would this be as simple as adding `"'%s' in parents" % (basedir, )`?

Fortunately, I have not had any files with this name outside my base folder, and my base folder is in the root as well..

> Files are healed in the sense that if there are more files with the same name, then all but one randomly selected are deleted

OK, that is definitely problematic.

**Comment by giomasce** [comment]
I extended the search to the whole Drive because I still have some files in subfolders and I want to see them. Of course a better approach would be to flatten things and then search only in the base folder, but as I said my code is not meant to be a general solution. It is just something that works for me.

By the way, while it may be problematic for you anyway, file healing only happens when files or folders are reached through the normal operation of googledriveannex. So, for example, it will not touch files other than those named `GPGHMACSHA1-*`. With folders the problem is a bit more complicated if the base path is a depth greater than 1.
